/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d8a1fcff1538143743a922870a8c0416)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
