/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8b44123230af8b01ed1a9b53ddb0b132)
interface __BaseEnv_Env {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
