import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { STYLES } from "../src/catalog/styles";
import {
  compileGlobalStyleCss,
  compileStyleCss,
} from "../src/style-css-compiler";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const outputJsPath = path.resolve(
  __dirname,
  "../src/generated/compiled-style-css.js",
);
const outputDtsPath = path.resolve(
  __dirname,
  "../src/generated/compiled-style-css.d.ts",
);
const outputTsShimPath = path.resolve(
  __dirname,
  "../src/generated/compiled-style-css.ts",
);

function formatRecord(name: string, value: Record<string, string>) {
  return [
    `export const ${name} = {`,
    ...Object.entries(value).map(
      ([style, css]) => `  ${JSON.stringify(style)}: ${JSON.stringify(css)},`,
    ),
    "} as const satisfies Record<StyleName, string>;",
  ].join("\n");
}

async function main() {
  const scoped: Record<string, string> = {};
  const global: Record<string, string> = {};

  for (const style of STYLES) {
    scoped[style.name] = await compileStyleCss(style.name);
    global[style.name] = await compileGlobalStyleCss(style.name);
  }

  mkdirSync(path.dirname(outputJsPath), { recursive: true });
  writeFileSync(
    outputJsPath,
    [
      "// This file is generated by packages/create-config/scripts/generate-compiled-style-css.ts",
      "// Do not edit manually.",
      "",
      formatRecord("compiledStyleCssByStyle", scoped).replace(
        " as const satisfies Record<StyleName, string>;",
        ";",
      ),
      "",
      formatRecord("compiledGlobalStyleCssByStyle", global).replace(
        " as const satisfies Record<StyleName, string>;",
        ";",
      ),
    ].join("\n"),
  );

  writeFileSync(
    outputDtsPath,
    [
      "// This file is generated by packages/create-config/scripts/generate-compiled-style-css.ts",
      "// Do not edit manually.",
      "",
      'import type { DesignSystemConfig } from "../config";',
      "",
      'type StyleName = DesignSystemConfig["style"];',
      "",
      "export declare const compiledStyleCssByStyle: Record<StyleName, string>;",
      "export declare const compiledGlobalStyleCssByStyle: Record<StyleName, string>;",
    ].join("\n"),
  );

  writeFileSync(
    outputTsShimPath,
    [
      'export {',
      "  compiledGlobalStyleCssByStyle,",
      "  compiledStyleCssByStyle,",
      '} from "./compiled-style-css.js";',
    ].join("\n"),
  );
}

await main();
