import { promises as fs } from "fs";
import path from "path";
import { preFlightInit } from "@/src/preflights/preflight-init";

import { clearRegistryContext } from "@/src/registry/context";

import { TEMPLATES, createProject } from "@/src/utils/create-project";
import * as ERRORS from "@/src/utils/errors";
import { getConfig } from "@/src/utils/get-config";
import { handleError } from "@/src/utils/handle-error";
import { highlighter } from "@/src/utils/highlighter";
import { logger } from "@/src/utils/logger";
import { Command } from "commander";
import { execa } from "execa";
import fsExtra from "fs-extra";
import { z } from "zod";

// process.on("exit", (code) => {
//   const filePath = path.resolve(process.cwd(), "components.json")

//   // Delete backup if successful.
//   if (code === 0) {
//     return deleteFileBackup(filePath)
//   }

//   // Restore backup if error.
//   return restoreFileBackup(filePath)
// })

// Default fallback registry endpoint for shadcn (expects /r)
const DEFAULT_REGISTRY_URL = "https://ui.bejamas.com/r";
export const DEFAULT_COMPONENTS_BASE_COLOR = "neutral";
const SHADCN_INIT_ARGS = ["init"] as const;

export const initOptionsSchema = z.object({
  cwd: z.string(),
  components: z.array(z.string()).optional(),
  yes: z.boolean(),
  defaults: z.boolean(),
  force: z.boolean(),
  silent: z.boolean(),
  isNewProject: z.boolean(),
  srcDir: z.boolean().optional(),
  cssVariables: z.boolean(),
  template: z
    .string()
    .optional()
    .refine(
      (val) => {
        if (val) {
          return TEMPLATES[val as keyof typeof TEMPLATES];
        }
        return true;
      },
      {
        message: "Invalid template. Please use 'next' or 'next-monorepo'.",
      },
    ),
  baseColor: z.string().optional(),
  baseStyle: z.boolean(),
});

export function buildShadcnInitInvocation(
  localShadcnPath: string,
  hasLocalShadcn: boolean,
) {
  if (hasLocalShadcn) {
    return {
      cmd: localShadcnPath,
      args: [...SHADCN_INIT_ARGS],
    };
  }

  return {
    cmd: "npx",
    args: ["-y", "shadcn@latest", ...SHADCN_INIT_ARGS],
  };
}

export function getDeprecatedBaseColorWarning(baseColor?: string) {
  if (!baseColor) {
    return null;
  }

  return [
    "The --base-color option is deprecated and ignored.",
    "Bejamas now aligns with shadcn CLI v4.",
    `Edit ${highlighter.info("components.json")} to change`,
    `${highlighter.info("tailwind.baseColor")} after init.`,
  ].join(" ");
}

export async function normalizeComponentsBaseColor(
  cwd: string,
  baseColor = DEFAULT_COMPONENTS_BASE_COLOR,
) {
  const filePath = path.resolve(cwd, "components.json");

  let originalContents: string;
  try {
    originalContents = await fs.readFile(filePath, "utf8");
  } catch {
    throw new Error(
      `Failed to read ${highlighter.info(
        filePath,
      )} after shadcn init. Make sure the command completed successfully and created a valid components.json file.`,
    );
  }

  let parsedConfig: Record<string, unknown>;
  try {
    const parsed = JSON.parse(originalContents);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error("Expected a JSON object.");
    }
    parsedConfig = parsed as Record<string, unknown>;
  } catch {
    throw new Error(
      `Failed to parse ${highlighter.info(
        filePath,
      )} after shadcn init. Expected a valid JSON object with a tailwind configuration.`,
    );
  }

  const tailwind = parsedConfig.tailwind;
  if (!tailwind || typeof tailwind !== "object" || Array.isArray(tailwind)) {
    throw new Error(
      `Invalid ${highlighter.info(
        filePath,
      )} generated by shadcn init. Expected a ${highlighter.info(
        "tailwind",
      )} object so Bejamas can normalize ${highlighter.info("baseColor")}.`,
    );
  }

  const normalizedConfig = {
    ...parsedConfig,
    tailwind: {
      ...(tailwind as Record<string, unknown>),
      baseColor,
    },
  };
  const normalizedContents = `${JSON.stringify(normalizedConfig, null, 2)}\n`;

  if (normalizedContents === originalContents) {
    return false;
  }

  await fs.writeFile(filePath, normalizedContents, "utf8");
  return true;
}

export const init = new Command()
  .name("init")
  .description("initialize your project and install dependencies")
  .argument("[components...]", "names, url or local path to component")
  .option(
    "-t, --template <template>",
    "the template to use. (next, next-monorepo)",
  )
  .option(
    "-b, --base-color <base-color>",
    "deprecated: accepted for compatibility but ignored. Edit components.json to change tailwind.baseColor.",
    undefined,
  )
  .option("-y, --yes", "skip confirmation prompt.", true)
  .option("-d, --defaults,", "use default configuration.", false)
  .option("-f, --force", "force overwrite of existing configuration.", false)
  .option(
    "-c, --cwd <cwd>",
    "the working directory. defaults to the current directory.",
    process.cwd(),
  )
  .option("-s, --silent", "mute output.", false)
  .option(
    "--src-dir",
    "use the src directory when creating a new project.",
    false,
  )
  .option(
    "--no-src-dir",
    "do not use the src directory when creating a new project.",
  )
  .option("--css-variables", "use css variables for theming.", true)
  .option("--no-css-variables", "do not use css variables for theming.")
  .option("--no-base-style", "do not install the base shadcn style.")
  .action(async (_components, opts) => {
    try {
      await runInit(opts);
    } catch (error) {
      logger.break();
      handleError(error);
    } finally {
      clearRegistryContext();
    }
  });

export async function runInit(
  options: z.infer<typeof initOptionsSchema> & {
    skipPreflight?: boolean;
  },
) {
  const baseColorWarning = getDeprecatedBaseColorWarning(options.baseColor);
  if (baseColorWarning && !options.silent) {
    logger.warn(baseColorWarning);
  }

  let newProjectTemplate;
  if (!options.skipPreflight) {
    const preflight = await preFlightInit(options);

    if (preflight.errors[ERRORS.MISSING_DIR_OR_EMPTY_PROJECT]) {
      const { projectPath, template } = await createProject(options);
      if (!projectPath) {
        process.exit(1);
      }
      options.cwd = projectPath;
      options.isNewProject = true;
      newProjectTemplate = template;
    }
  }

  if (newProjectTemplate) {
    const projectPath = {
      "astro-monorepo": "apps/web",
      "astro-with-component-docs-monorepo": "apps/web",
      astro: "",
    } as const;
    options.cwd = path.resolve(options.cwd, projectPath[newProjectTemplate]);

    logger.log(
      `${highlighter.success(
        "Success!",
      )} Project initialization completed.\nYou may now add components.`,
    );

    return await getConfig(options.cwd);
  }

  // const projectConfig = await getProjectConfig(options.cwd, projectInfo);

  const shadcnBin = process.platform === "win32" ? "shadcn.cmd" : "shadcn";
  const localShadcnPath = path.resolve(
    options.cwd,
    "node_modules",
    ".bin",
    shadcnBin,
  );

  try {
    const env = {
      ...process.env,
      REGISTRY_URL: process.env.REGISTRY_URL || DEFAULT_REGISTRY_URL,
    };
    const hasLocalShadcn = await fsExtra.pathExists(localShadcnPath);
    const invocation = buildShadcnInitInvocation(
      localShadcnPath,
      hasLocalShadcn,
    );

    await execa(invocation.cmd, invocation.args, {
      stdio: "inherit",
      cwd: options.cwd,
      env,
    });
  } catch (err) {
    // shadcn already printed the detailed error to stdio, avoid double-reporting
    process.exit(1);
  }

  await normalizeComponentsBaseColor(options.cwd);
}
